using WhatsAppBusiness.Domain.ValueObjects;

namespace WhatsAppBusiness.Application.DTOs;

/// <summary>
/// Data transfer object for Message entity
/// </summary>
public class MessageDto
{
    /// <summary>
    /// Gets or sets the message ID
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// Gets or sets the conversation ID
    /// </summary>
    public Guid ConversationId { get; set; }

    /// <summary>
    /// Gets or sets the message content
    /// </summary>
    public string Content { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the message type
    /// </summary>
    public MessageType Type { get; set; }

    /// <summary>
    /// Gets or sets the message direction
    /// </summary>
    public MessageDirection Direction { get; set; }

    /// <summary>
    /// Gets or sets when the message was sent
    /// </summary>
    public DateTime SentAt { get; set; }

    /// <summary>
    /// Gets or sets when the message was delivered
    /// </summary>
    public DateTime? DeliveredAt { get; set; }

    /// <summary>
    /// Gets or sets when the message was read
    /// </summary>
    public DateTime? ReadAt { get; set; }

    /// <summary>
    /// Gets or sets whether the message was generated by AI
    /// </summary>
    public bool IsFromAI { get; set; }

    /// <summary>
    /// Gets or sets the WhatsApp message ID
    /// </summary>
    public string? WhatsAppMessageId { get; set; }
}
