using WhatsAppBusiness.Domain.Common;
using WhatsAppBusiness.Domain.ValueObjects;

namespace WhatsAppBusiness.Domain.Entities;

/// <summary>
/// Represents a message in a conversation
/// </summary>
public class Message : Entity
{
    /// <summary>
    /// Gets the conversation ID this message belongs to
    /// </summary>
    public Guid ConversationId { get; private set; }

    /// <summary>
    /// Gets the message content
    /// </summary>
    public MessageContent Content { get; private set; }

    /// <summary>
    /// Gets the message type
    /// </summary>
    public MessageType Type { get; private set; }

    /// <summary>
    /// Gets the message direction
    /// </summary>
    public MessageDirection Direction { get; private set; }

    /// <summary>
    /// Gets the date and time when the message was sent
    /// </summary>
    public DateTime SentAt { get; private set; }

    /// <summary>
    /// Gets the date and time when the message was delivered
    /// </summary>
    public DateTime? DeliveredAt { get; private set; }

    /// <summary>
    /// Gets the date and time when the message was read
    /// </summary>
    public DateTime? ReadAt { get; private set; }

    /// <summary>
    /// Gets whether the message was generated by AI
    /// </summary>
    public bool IsFromAI { get; private set; }

    /// <summary>
    /// Gets the WhatsApp message ID
    /// </summary>
    public string? WhatsAppMessageId { get; private set; }

    private Message()
    {
        Content = null!;
    }

    private Message(
        Guid id,
        Guid conversationId,
        MessageContent content,
        MessageType type,
        MessageDirection direction,
        bool isFromAI,
        DateTime sentAt)
        : base(id)
    {
        ConversationId = conversationId;
        Content = content;
        Type = type;
        Direction = direction;
        IsFromAI = isFromAI;
        SentAt = sentAt;
    }

    /// <summary>
    /// Creates a new message
    /// </summary>
    /// <param name="conversationId">The conversation ID</param>
    /// <param name="content">The message content</param>
    /// <param name="type">The message type</param>
    /// <param name="direction">The message direction</param>
    /// <param name="isFromAI">Whether the message is from AI</param>
    /// <returns>A new Message instance</returns>
    public static Message Create(
        Guid conversationId,
        MessageContent content,
        MessageType type,
        MessageDirection direction,
        bool isFromAI = false)
    {
        return new Message(
            Guid.NewGuid(),
            conversationId,
            content,
            type,
            direction,
            isFromAI,
            DateTime.UtcNow);
    }

    /// <summary>
    /// Sets the WhatsApp message ID
    /// </summary>
    public void SetWhatsAppMessageId(string whatsAppMessageId)
    {
        if (string.IsNullOrWhiteSpace(whatsAppMessageId))
            throw new ArgumentException("WhatsApp message ID cannot be empty", nameof(whatsAppMessageId));

        WhatsAppMessageId = whatsAppMessageId;
    }

    /// <summary>
    /// Marks the message as delivered
    /// </summary>
    public void MarkAsDelivered()
    {
        if (!DeliveredAt.HasValue)
            DeliveredAt = DateTime.UtcNow;
    }

    /// <summary>
    /// Marks the message as read
    /// </summary>
    public void MarkAsRead()
    {
        if (!DeliveredAt.HasValue)
            DeliveredAt = DateTime.UtcNow;

        if (!ReadAt.HasValue)
            ReadAt = DateTime.UtcNow;
    }
}
